### ISSUE TITLE
[MultiSelectField] - Immediately apply changes freezes page

### ISSUE THREAD

**Issue by sergejbog** [techniq/svelte-ux#507] opened 2024-11-02 04:21 UTC
If you try to select an option for the multiselect field it freezes the whole page and makes the tab unresponsive. See the video below.

https://github.com/user-attachments/assets/337807fe-f258-48b8-b24e-ffb433c554c6

**Comment by sergejbog** [comment] 2024-11-02 04:25
I just saw that the same problem exists on the MultiSelect component as well.

**Comment by techniq** [comment] 2024-11-02 20:47
Thanks for the report @sergejbog .  I was tracking this in issue #144 and is one of the last regressions with Svelte 5.  It's due to an infinite loop on apply/change that I need to investigate.  Should have a solution this weekend once I get some time to dig into it.

**Comment by techniq** [comment] 2024-11-03 03:39
Resolved in [0.75.4](https://github.com/techniq/svelte-ux/releases/tag/svelte-ux%400.75.4) via https://github.com/techniq/svelte-ux/commit/2524959f59f72ce968624f3235e0b64ba30a88b6

**Closed by techniq** 2024-11-03 03:39 UTC
